import logging
import re
import json

from functools import partial
from itertools import groupby, chain
from typing import Any, TYPE_CHECKING, Mapping, Callable

from rita.utils import ExtendedOp
from rita.types import Rules, Patterns

logger = logging.getLogger(__name__)

ParseFn = Callable[[Any, "SessionConfig", ExtendedOp], str]


if TYPE_CHECKING:
    # We cannot simply import SessionConfig because of cyclic imports
    from rita.config import SessionConfig


class RuleCompileError(Exception):
    """
    Raised when a rule cannot be turned into a valid regex pattern
    """


VALID_LABEL = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Matches bare regex metacharacters, but not ones which are already
# escaped (eg. `J\.` produced by rita.modules.names must stay as-is)
BARE_METACHAR = re.compile(r"(?<!\\)([.^$*+?{}\[\]()|])")


def escape_literal(value: str) -> str:
    """
    Escape regex metacharacters in a user-supplied literal,
    keeping already-escaped sequences untouched
    """
    return BARE_METACHAR.sub(r"\\\1", value)


def apply_operator(syntax, op: ExtendedOp) -> str:
    if op.empty():
        return syntax

    elif str(op) == "!":
        # Negation: a word which doesn't match the given syntax
        return r"((?!{0})\w+)".format(syntax)
    else:
        return syntax + str(op)


def any_of_parse(lst, config: "SessionConfig", op: ExtendedOp) -> str:
    alts = "|".join(sorted([escape_literal(item) for item in lst],
                           key=lambda x: (-len(x), x)))
    if str(op) == "!":
        # Negation has to be built from the raw alternatives:
        # the `(^|\s)` prefix used below can never match mid-pattern
        # and would make the lookahead pass for any word
        return r"((?!(?:{0})\b)\w+)".format(alts)
    clause = r"((^|\s)(({0})\s?))".format(alts)
    return apply_operator(clause, op)


def regex_parse(r, config: "SessionConfig", op: ExtendedOp) -> str:
    if not r:
        raise RuleCompileError("Empty regex pattern")

    if op.local_regex_override:
        return local_regex_parse(r, config, op)
    else:
        initial = "(" + r + r"\s?" + ")"
        return apply_operator(initial, op)


def local_regex_parse(r, config: "SessionConfig", op: ExtendedOp) -> str:
    if r[0] == "^" and r[-1] == "$":  # Fully strictly defined string?
        pattern = r[1:-1]
    elif r[0] == "^":  # We define start of the string
        pattern = r[1:] + r"\w*"
    elif r[-1] == "$":  # We define end of string
        pattern = r"\w*" + r[:-1]
    else:  # We define string inside word
        pattern = r"\w*" + r + r"\w*"

    initial = "(" + r"\b" + pattern + r"\b" + r"\s?" + ")"
    return apply_operator(initial, op)


def not_supported(key, *args, **kwargs) -> str:
    raise RuntimeError(
        "Rule '{0}' is not supported in standalone mode"
        .format(key)
    )


def person_parse(config: "SessionConfig", op: ExtendedOp) -> str:
    return apply_operator(r"([A-Z]\w+\s?)", op)


def entity_parse(value, config: "SessionConfig", op: ExtendedOp) -> str:
    if value == "PERSON":
        return person_parse(config, op=op)
    else:
        return not_supported(value)


def punct_parse(_, config: "SessionConfig", op: ExtendedOp) -> str:
    return apply_operator(r"([.,!;?:]\s?)", op)


def word_parse(value, config: "SessionConfig", op: ExtendedOp) -> str:
    initial = r"({}\s?)".format(escape_literal(value))
    return apply_operator(initial, op)


def fuzzy_parse(r, config: "SessionConfig", op: ExtendedOp) -> str:
    # Values are regex fragments generated by rita.modules.fuzzy - must not be escaped
    return apply_operator(r"(({0})[.,?;!]?\s?)".format("|".join(r)), op)


def phrase_parse(value, config: "SessionConfig", op: ExtendedOp) -> str:
    return apply_operator(r"({}\s?)".format(escape_literal(value)), op)


def nested_parse(values, config: "SessionConfig", op: ExtendedOp) -> str:
    from rita.macros import resolve_value
    (_, patterns) = rules_to_patterns("", [resolve_value(v, config=config)
                                           for v in values], config=config)
    return r"(?P<g{}>{})".format(config.new_nested_group_id(), "".join(patterns))


def any_parse(_, config: "SessionConfig", op: ExtendedOp) -> str:
    return regex_parse(r".*", config, op)


PARSERS: Mapping[str, ParseFn] = {
    "any_of": any_of_parse,
    "any": any_parse,
    "value": word_parse,
    "regex": regex_parse,
    "entity": entity_parse,
    "lemma": partial(not_supported, "LEMMA"),
    "pos": partial(not_supported, "POS"),
    "punct": punct_parse,
    "fuzzy": fuzzy_parse,
    "phrase": phrase_parse,
    "nested": nested_parse,
}


def rules_to_patterns(label: str, data: Patterns, config: "SessionConfig"):
    logger.debug("data: {}".format(data))
    return (
        label,
        [PARSERS[t](d, config, op) for (t, d, op) in data],
    )


class RuleExecutor(object):
    def __init__(self, patterns, config, regex_impl=re, max_workers=None, match_timeout=None):
        # `max_workers` is kept for backwards compatibility and is unused:
        # matching runs sequentially, which is faster for GIL-bound regex
        # and keeps result order deterministic
        self.config = config
        self.regex_impl = regex_impl
        self.match_timeout = match_timeout
        self.patterns = [self.compile(label, rules)
                         for label, rules in patterns]
        self.raw_patterns = patterns

    def compile(self, label, rules):
        if not VALID_LABEL.match(label):
            raise RuleCompileError(
                "Invalid rule label: '{0}'. "
                "A label must be a valid regex group name: "
                "letters, digits and underscores, not starting with a digit".format(label)
            )

        flags = self.regex_impl.DOTALL
        if self.config.ignore_case:
            flags = flags | self.regex_impl.IGNORECASE

        indexed_rules = ["(?P<s{}>{})".format(i, r) if not r.startswith("(?P<") else r
                         for i, r in enumerate(rules)]
        regex_str = r"(?P<{0}>{1})".format(label, "".join(indexed_rules))
        try:
            return self.regex_impl.compile(regex_str, flags)
        except Exception as ex:
            raise RuleCompileError(
                "Failed to compile rule '{0}': {1}\n"
                "Generated pattern: {2}".format(label, ex, regex_str)
            ) from ex

    def _finditer(self, pattern, text):
        if self.match_timeout is not None:
            try:
                return pattern.finditer(text, timeout=self.match_timeout)
            except TypeError:
                raise RuntimeError(
                    "`match_timeout` requires a regex implementation which supports it, "
                    "eg. the third-party `regex` module (pass `regex_impl=regex`)"
                )
        return pattern.finditer(text)

    def _match_task(self, pattern, text, include_submatches):
        def gen():
            for match in self._finditer(pattern, text):
                def submatches():
                    for k, v in match.groupdict().items():
                        if not v or v.strip() == "":
                            continue
                        yield {
                            "key": k,
                            "text": v.strip(),
                            "start": match.start(k),
                            "end": match.end(k)
                        }

                yield {
                    "start": match.start(),
                    "end": match.end(),
                    "text": match.group().strip(),
                    "label": match.lastgroup,
                    "submatches": sorted(list(submatches()), key=lambda x: x["start"]) if include_submatches else []
                }
        return list(gen())

    def _results(self, text, include_submatches):
        for pattern in self.patterns:
            yield self._match_task(pattern, text, include_submatches)

    def execute(self, text, include_submatches=True):
        results = sorted(chain(*self._results(text, include_submatches)), key=lambda x: x["start"])
        for k, g in groupby(results, lambda x: x["start"]):
            group = list(g)
            if len(group) == 1:
                yield group[0]
            else:
                data = sorted(group, key=lambda x: -x["end"])
                yield data[0]

    @staticmethod
    def load(path, regex_impl=re):
        from rita.config import SessionConfig
        config = SessionConfig()
        patterns = []
        with open(path, "r") as f:
            for line_no, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                except ValueError as ex:
                    raise ValueError(
                        "Invalid JSON on line {0} of '{1}': {2}".format(line_no, path, ex)
                    ) from ex

                if "config" in obj and "label" not in obj:
                    for k, v in obj["config"].items():
                        config.set_config(k, v)
                elif "label" in obj and "rules" in obj:
                    patterns.append((obj["label"], obj["rules"]))
                else:
                    raise ValueError(
                        "Unexpected object on line {0} of '{1}': "
                        "expected a config header or a rule with 'label' and 'rules'".format(line_no, path)
                    )
        return RuleExecutor(patterns, config, regex_impl=regex_impl)

    def save(self, path):
        with open(path, "w") as f:
            f.write("{0}\n".format(json.dumps({
                "config": {"ignore_case": self.config.ignore_case}
            })))
            for pattern in self:
                f.write("{0}\n".format(json.dumps(pattern)))

    def __iter__(self):
        for label, rules in self.raw_patterns:
            yield {"label": label, "rules": rules}


def compile_rules(rules: Rules, config: "SessionConfig", regex_impl=re, **kwargs) -> RuleExecutor:
    logger.info("Using standalone rule implementation")
    patterns = [rules_to_patterns(*group, config=config) for group in rules]
    executor = RuleExecutor(patterns, config, regex_impl=regex_impl,
                            match_timeout=kwargs.get("match_timeout"))
    return executor
